version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/notion"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=qwerty007"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: notion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007

