server:
    port: ${PORT:8000}

base-url: /api

spring:
    application:
        name: notion

    datasource:
        hikari.maximum-pool-size: 10
        url: jdbc:postgresql://localhost:5432/notion
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    liquibase:
        enabled: true
        change-log: classpath:liquibase/changelog.yml

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                format_sql: true
                jdbc.batch_size: 30

    logging:
        level:
            root: INFO
            web: DEBUG
