server:
    port: ${PORT:8090}

base-url: /api

spring:
    application:
        name: notion

    datasource:
        hikari.maximum-pool-size: 10
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driverClassName: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: false
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        properties:
            hibernate:
                format_sql: true
                jdbc.batch_size: 30

    logging:
        level:
            root: INFO
            web: DEBUG
