server:
    port: ${PORT:8090}

base-url: /api

spring:
    application:
        name: notion

    datasource:
        username: ""
        password: ""
        url: jdbc:h2:./notionDB
        driver-class-name: org.h2.Driver

    h2:
        console:
            enabled: true
            path: /h2-console/
            settings:
                web-allow-others: true

    jpa:
        hibernate:
            ddl-auto: update

        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect

    mvc:
        hiddenmethod:
            filter:
                enabled: true

    logging:
        level:
            root: INFO
            web: DEBUG
